name: Allure Report

on:
  push:
    branches:
      - main  # Укажите вашу ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Выберите подходящую версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install allure-pytest

#    - name: Run tests and generate Allure report
#      run: |
#        pytest --alluredir=./allure-results
#        allure generate ./allure-results --clean -o ./allure-report

    - name: Serve Allure report using Docker
      uses: docker://allureframework/allure2:latest
      with:
        args: serve ./allure-report
