name: Allure Report

on:
  push:
    branches:
      - main  # Укажите ваши ветки по необходимости

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Выберите нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install allure-pytest

#    - name: Run tests and generate Allure report
#      run: |
#        pytest --alluredir=./allure-results
#        allure generate ./allure-results --clean -o ./allure-report

    - name: Install Allure command-line
      run: |
        wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.zip
        unzip allure-commandline-2.14.0.zip
        sudo cp -r allure-2.14.0/bin/* /usr/local/bin/
        rm -rf allure-2.14.0 allure-commandline-2.14.0.zip

    - name: Serve Allure report
      run: |
        allure serve ./allure-report
    
